app/measurement/controllers.py
from flask import Flask, Blueprint, request, render_template, url_for, redirect, jsonify, send_from_directory, after_this_request
from app import app, db
from app.measurement.models import Measurement, Measured_person, Measuring_station, Measured_values
from app.auth.models import User
from app.experiments.models import Experiments
from app.measurement.forms import NewMeasurementForm, EditMeasurementForm, NewMeasuringStation, CodeGenerator
from sqlalchemy import desc
from flask_login import login_required, current_user
from os import urandom, path, remove
import os
import binascii
from flask_weasyprint import HTML, render_pdf
import pyqrcode
import json
import xlsxwriter
import statistics
import shutil
from flask_wtf import Form
from wtforms import StringField, SubmitField, BooleanField  # Import Form elements such as TextField and BooleanField (optional)
from wtforms.validators import DataRequired, length  # Import Form validators
from wtforms.fields.html5 import DateTimeLocalField, DateTimeField
from werkzeug.utils import secure_filename
import flask_excel as excel
import datetime
from datetime import timedelta

from app.qrgenerator import controllers

measurement = Blueprint('measurement', __name__, template_folder='templates', url_prefix='/app')

@measurement.route('/measurement/go')
@login_required
def go_measure():
    """Page shows measure forms for data insertion"""
    measureToday = Measurement.allMeasurementToday()
    return render_template("go_measure.html", data=measureToday)


@measurement.route('/measurement/new-data/<int:measurement_id>', methods=['GET', 'POST'])
@login_required
def new_data(measurement_id):
    """Page shows measure forms for data insertion"""
    experimentIDs = Measuring_station.getExperimentsId(measurement_id, current_user.id)
    data = []
    names = []
    experiment_ids = []
    
    #dynamic forms
    class DynamicForm(Form): pass
    
    setattr(DynamicForm, "person_id", StringField("ID", [DataRequired()]))
    for index, ex in enumerate(experimentIDs):
        experiment_ids.append(ex.experiments_id)
        exp = Experiments.getExperiment(ex.experiments_id)
        setattr(DynamicForm, "field"+str(index), StringField("name"))
        names.append(exp.experimentName)
        data.append(exp.experimentScheme)
    setattr(DynamicForm, "submit", SubmitField("Submit"))
    
    form = DynamicForm(request.form)
    
    if form.data and form.validate_on_submit():
        personID = ""
        for index, field in enumerate(form):
            #nacteni id hash z formulare
            if index is 0:
                personID = field.data
            elif index > 0:
                
                if field.name == "csrf_token" or field.name == "submit":
                    continue
                exp = Experiments.getExperiment(experimentIDs[index-1].experiments_id)
                
                if exp.experimentName == 'Registrace' or exp.experimentName == 'registrace' or exp.experimentName == 'Registration' or exp.experimentName == 'registrace':
                    Measured_person.registerPerson(current_user.id, personID, measurement_id, experimentIDs[index-1].experiments_id, field.data)
                else:
                    #return str(field.data)
                    Measured_person.saveData(current_user.id, personID, measurement_id, experimentIDs[index-1].experiments_id, field.data)
                    
    form.person_id.data = ""
    return render_template("new_data.html", data=data, names=names, form=form, measurementID = measurement_id, experiment_ids = experiment_ids)

@measurement.route('/project')
@login_required
def project():
    """Show info about project."""

    return render_template("project.html")


@measurement.route('/planning/show', methods=['GET', 'POST'])
@login_required
def measure_planning():
    """Show all future (planned) measuring"""

    form_add = NewMeasurementForm(request.form)
    form_edit = EditMeasurementForm(request.form)
    form_task = NewMeasuringStation(request.form)
    data = db.session.query(Measurement).order_by(Measurement.begin.desc())

    if form_edit.edit.data and form_edit.validate_on_submit():
        measure_inst = db.session.query(Measurement).filter_by(id=form_edit.measure_id.data).first()
        if measure_inst:
            measure_inst.begin = form_edit.begin_e.data
            measure_inst.end = form_edit.end_e.data
            measure_inst.town = form_edit.town_e.data
            measure_inst.street = form_edit.street_e.data
            measure_inst.number = form_edit.number_e.data
            measure_inst.institution = form_edit.institution_e.data
            db.session.flush()
            db.session.commit()

    return render_template("planning.html", data=data, form_add=form_add, form_edit=form_edit, form_task=form_task)


@measurement.route('/name_autocomplete', methods=['GET'])
def name_autocomplete():
    """Finds proper name of experiments matching with input and sends it as a list"""
    search = request.args.get('qn')
    if search == " ":
        query = db.session.query(Experiments.experimentName)
    else:
        query = db.session.query(Experiments.experimentName).filter(
            Experiments.experimentName.ilike('%' + str(search) + '%'))

    results = [mv[0] for mv in query.all()]
    return jsonify(matching_results_n=results)


@measurement.route('/executor_autocomplete', methods=['GET'])
def executor_autocomplete():
    """Finds proper name of experiment executor matching with input and sends it as a list"""
    search = request.args.get('qe')
    if search == " ":
        query = db.session.query(User.name)
    else:
        query = db.session.query(User.name).filter(User.name.ilike('%' + str(search) + '%'))

    results = [mv[0] for mv in query.all()]
    return jsonify(matching_results_e=results)


@measurement.route('/show_experiments')
@login_required
def show_experiments():
    """Finds names of experiment executors and sends it as a list"""

    query = db.session.query(Experiments.experimentName).order_by(Experiments.id)
    results = [mv[0] for mv in query.all()]

    return jsonify(result=results)


@measurement.route('/show_executors')
@login_required
def show_executors():
    """Finds names of experiment executors and sends it as a list"""

    query = db.session.query(User.name).order_by(User.id)
    results = [mv[0] for mv in query.all()]

    return jsonify(result=results)


@measurement.route('/planning/detail/show/<int:id_detail>')
@login_required
def show_measurement_detail(id_detail):
    """Show pop up detail TODO: !!!"""


@measurement.route('/planning_add', methods=['GET', 'POST'])
@login_required
def planning_add():
    """Add new measuring to plan TODO: kontrola prijatych dat, vyresit vytvoreni konstruktoru"""
    form_add = NewMeasurementForm(request.form)
    form_task = NewMeasuringStation(request.form)
    result = -1

    if form_add.add and form_add.validate_on_submit():
        measure_inst = Measurement(
            institution=form_add.institution.data,
            begin=form_add.begin.data,
            end=form_add.end.data,
            town=form_add.town.data,
            street=form_add.street.data,
            number=form_add.number.data

            # created_by_user_id = 1
            # db.session.query(User).filter_by(id = currnet_user.get_id())
        )
        db.session.add(measure_inst)
        db.session.commit()
        result = measure_inst.id

    elif form_task.validate_on_submit():
        experiment_id = db.session.query(Experiments.id).filter_by(experimentName=form_task.experimentName.data).first()
        if experiment_id:
            query = db.session.query(User.id).filter(User.name.ilike('%' + str(form_task.experimentExecutor.data) + '%'))
            executor_id = [mv[0] for mv in query.all()].pop()
            if executor_id:
                task_inst = Measuring_station(
                    measurement_id=form_task.measurement_id.data,
                    user_id=executor_id,
                    experiments_id=experiment_id.id
                )
                db.session.add(task_inst)
                db.session.commit()
                result = 1

    return jsonify(result=result)


@measurement.route('/planning/edit/<int:id_edit>')
@login_required
def edit_planned_measurement(id_edit):
    """Show pop up window for edit measurement TODO: !!! ajax:("""
    return redirect('app/planning/show')


@measurement.route('/planning/remove/<int:id_remove>')
@login_required
def remove_planned_measurement(id_remove):
    """Remove selected measurement"""

    Measurement.query.filter_by(id=id_remove).delete()
    db.session.commit()
    return redirect('app/planning/show')


@measurement.route('/measured/show')
@login_required
def measured():
    """Show table with measuring"""
    data = db.session.query(Measurement).order_by(desc(Measurement.date_created))
    return render_template("measured.html", data=data)


@measurement.route('/measurement/edit/<int:id_edit>')
@login_required
def edit_measurement(id_edit):
    """Show pop up window for edit measurement TODO: !!! ajax:("""
    return redirect('app/planning/show')


@measurement.route('/measurement/remove/<int:id_remove>')
@login_required
def remove_measurement(id_remove):
    """Remove selected measurement"""

    Measurement.query.filter_by(id=id_remove).delete()
    db.session.commit()
    return redirect('app/planning/show')



# uz se nevyuziva
@measurement.route('/measured/measured_persons')
@login_required
def measured_persons():
    """Show measured persons"""
    names = []
    data = db.session.query(Measured_person)
    for d in data:
        """vyber id mereni a vypis jeho nazev"""
        m = Measured_values.getOneValue(d.id) # measurement_id
        measurement_id = m.measurement_id
        print(measurement_id)
        names.append(Measurement.getMeasurementById(measurement_id))
        
    return render_template("measured_persons.html", data=zip(data, names))

app/measurement/templates/all_projects.html
{% extends "layout.html" %}

		{% block title %}Measurement{% endblock %}
		{% block includes %}
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
            <link rel="stylesheet" href="{{ url_for('static', filename='popup.css') }}"> <!-- Resource style -->
            <link rel="stylesheet" href="{{ url_for('static', filename='table.css') }}"> <!-- Resource style -->
            <link rel="stylesheet" href="{{ url_for('static', filename='timeline.css') }}"> <!-- Resource style -->
            <link href="//code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" rel="Stylesheet">
            <script src="//code.jquery.com/jquery-2.2.0.min.js"></script>
            <script src="//code.jquery.com/ui/1.10.2/jquery-ui.js" ></script>
            <script src="{{ url_for('static', filename='js/show_div.js') }}"></script>
		{% endblock %}

		
		{% block content %}
		
<section>
	<h1 class="page-header">Measurement</h1>
    <form action="{{ url_for('measurement.export') }}" method="post">
        <table class="table table-hover">
            <tr>
                <th>Name</th>
                <th>Date</th>
                <th>Town</th>
                <th>Data</th>
                <th>Stats</th>
                <th style="text-align:center; vertical-align:middle;">Export</th>
                <th>Delete</th>
            </tr>
            {% for d in data %}
            <tr>
                <td>{{d.institution}}</td>
                <td>{{ d.begin.strftime('%d/%m/%y') }}</td>
                <td>{{ d.town }}</td>
                <td><a href="{{ url_for('measurement.project_persons', measurementID=d.id) }}">data</a></td>
                <td><a href="{{ url_for('measurement.stats', measurementID=d.id) }}">view</a></td>
                <td style="text-align:center; vertical-align:middle;"><input type="checkbox" name="measurement" value="{{ d.id }}" /></td>
                <td><a href="#"><span class="fa fa-trash"></span></a></td>
            </tr>
            {% endfor %}
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td style="text-align:center; vertical-align:middle;"><input type="submit" value="Download" class="btn"></td>
                <td></td>
            </tr>
        </table>
    </form>	
	</section> <!-- timeline -->
		
{% endblock %}

app/measurement/templates/export.html
{% extends "layout.html" %} 


{% block content %}

    <h1>Export</h1>
    <p>In progress...</p>

{% endblock %}

app/measurement/templates/export_2.html
{% extends "layout.html" %} 


{% block content %}

    <h1>Export</h1>
    <p>In progress...</p>

{% endblock %}

app/measurement/templates/import2.html
{% extends "layout.html" %} 


{% block content %}

    <h1>Excel file upload (csv, tsv, csvz, tsvz only)</h1>
    <form action="{{ url_for('measurement.importData2') }}" method=post enctype=multipart/form-data>
    <input type="text" name="measurement_id"><br>
    <input type=file name=file>
    <input type=submit value=Upload>
   </form>

{% endblock %}

app/measurement/templates/layout.html
{% macro link_to(endpoint, text) -%}
<a href="{{ url_for(endpoint, **kwargs) }}">{{ text|safe }}</a>
{%- endmacro %} 


<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>{% block title %}{% endblock %}</title>
		<link href='https://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="{{ url_for('static', filename='appstyle.css') }}"> <!-- Resource style -->
		{% block includes %}{% endblock %}
	</head>
	<body>
		<div>
			<header>Header
			
			</header>
			<nav>
				<div class="logo">Projektové dny</div>
				<h3>Navigation</h3>
				<ul class="menu">
					<li><a href="{{ url_for('measurement.project') }}" class="menu-item">Projekt</a></li>
					<li><a href="{{ url_for('measurement.measure_planning') }}" class="menu-item"><span class="i-active"></span>Měření</a></li>
					<ul class="menu">
						<li><a href="{{ url_for('measurement.measure_planning') }}" class="submenu-item">Plánování měření</a></li>
						<li><a href="{{ url_for('measurement.measured') }}" class="submenu-item">Proběhlá měření</a></li>
						<li><a href="{{ url_for('measurement.measured_persons') }}" class="submenu-item">Měřené osoby</a></li>
					</ul>
					<li><a href="{{ url_for('experiments.get_experiments') }}" class="menu-item">Experimenty</a></li>
                    <li><a href="{{ url_for('equipment.get_equipment') }}" class="menu-item">Přístroje</a></li>
					<li><a href="#" class="menu-item">Nastavení</a></li>
					<li><a href="{{ url_for('admin.show_all_users') }}" class="menu-item">Administrace</a></li>
				</ul>
				<div class="sidefooter"></div>
			</nav>
			<main>

				{% block content %}{% endblock %}

			</main>
			<aside>
				Aside Content Box</br>
				{{ link_to('auth.logout', "Logout") }}
			</aside>
			<footer>Footer Bar</footer>  
		</div>
	</body>
</html>

app/measurement/templates/measured.html
{% extends "layout.html" %}

	{% block title %}Měření{% endblock %}
		{% block includes %}
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="{{ url_for('static', filename='popup.css') }}"> <!-- Resource style -->
		<link rel="stylesheet" href="{{ url_for('static', filename='table.css') }}"> <!-- Resource style -->
		<script src="//code.jquery.com/jquery-2.2.0.min.js"></script>
        <!--<script src="//code.jquery.com/ui/1.10.2/jquery-ui.js" ></script>-->
        <script src="{{ url_for('static', filename='js/show_div.js') }}"></script>
	{% endblock %}

	{% block content %}

		<div id="show_popup" class="overlay">
			<div class="popup">
				<h2>Detail proběhlého měření</h2>
				<a class="close" href="#" onclick="unloadShowDetail()">&times;</a>
				<div class="content">

				</div>
			</div>
		</div>


		<h1 class="page-header">Proběhlá měření</h1>
		
		<table>
			<tr>
				<th>Instituce</th>
				<th>Datum</th>
				<th>Město</th>
				<th class="column delete">Smazat</th>
			</tr>

			{% for d in data %}
			<tr>
				<td class="column institution"><a href="#" title="Ukázat detail" onclick="loadShowDetail()">{{d.institution}}</a></td>
				<td class="column date">{{ d.begin.strftime('%d/%m/%y') }}</td>
				<td class="column city">{{ d.town }}</td>
				<td class="column delete"><a href="{{ url_for('measurement.remove_measurement', id_remove=d.id) }}"><span class="fa fa-trash"></span></a></td>
			</tr>
			{% endfor %}
		</table>
		
	{% endblock %}

app/measurement/templates/measured_persons.html
{% extends "layout.html" %}

		{% block title %}Naměřené osoby{% endblock %}
		{% block includes %}
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="{{ url_for('static', filename='popup.css') }}"> <!-- Resource style -->
		<link rel="stylesheet" href="{{ url_for('static', filename='table.css') }}"> <!-- Resource style -->
		{% endblock %}

		{% block content %}
		<h1 class="page-header">Measurement</h1>
		
		<table class="table">
			<tr>
				<th>Person ID</th>
				<th>Date</th>
				<th>Measurement</th>
				<th>Data</th>
				<!--<th>Editovat</th>-->
				<th>Delete</th>
			</tr>
			{% for d, n in data %}
			<tr>
				<td>{{d.personHash}}</td>
				<td>{{n.begin}}</td>
				<td>{{n.institution}}</td>
				<td><a href="{{ url_for('measurement.showPersonDetail', hexID=d.personHash) }}">data</a></td>
				<!--<td><a href="{{ url_for('measurement.edit_measurement', id_edit=d.id) }}"><span class="fa fa-pencil"></span></a></td>-->
				<td><a href="{{ url_for('measurement.remove_measurement', id_remove=d.id) }}"><span class="fa fa-trash"></span></a></td>
			</tr>
			{% endfor %}
		</table>
		
		{% endblock %}

app/measurement/templates/measurement_detail.html
{% extends "layout.html" %}

		{% block title %}Measurement{% endblock %}
		{% block includes %}
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="{{ url_for('static', filename='popup.css') }}"> <!-- Resource style -->
		<link rel="stylesheet" href="{{ url_for('static', filename='table.css') }}"> <!-- Resource style -->
		
        <style>
        
        h4 {
            color: #57a5bf;
        }
        
        .files {
            width: 60%;
        }
        
        .file {
            text-align: center;
            color: #aaa;
            
        }
        
        .file > a {
            color: #aaa;
        }
        
        .file > a:hover {
            color: #57a5bf;
            text-decoration: none;
        }
        
        .file-icon {
            font-size: 4em;
            color: #aaa;
        }
        
        .file-icon:hover {
            color: #57a5bf;
        }
        
        .codes {
            padding: 1.3em;
            font-family: monospace;
            color: #aaa;
            background-color: #f3f3f3;
            overflow: auto;
            max-height: 30em;
            margin-top: 2em;
            margin-bottom: 2em;
        }
        
        .inputLength {
            width: 10em;
            margin-bottom: 0.6em;
        }
        
        
        </style>
        
        {% endblock %}

		{% block content %}
		<h1 class="page-header">Project - {{ data.institution }}</h1>
        
		
        <h4>Details</h4>
        <span class="fa fa-map-marker"> {{data.street}} {{data.number}} {{data.town}}</span><br>
        <span class="fa fa-calendar-o"> {{data.begin}}</span>


        <h4>Person Codes</h4>

        <form action="{{ url_for('measurement.planning_detail', id_measurement=data.id) }}" method=post>
        
        {{ form.hidden_tag() }}
        {{ form.codeNumbers(class_="inputLength blue-input", placeholder="Number of codes") }} <br>
        {{ form.generate(class_="small-button blue-button") }}
        
        </form>
        
        <div class="codes">
            {% for code in codes %}
                {% if loop.index0 % 6 == 0 %}
                    <div class="row">
                {% endif %}
                <div class="col-md-2">{{ code }}</div>
                {% if (loop.index0 + 1) % 6 == 0 and loop.index0 != 0 or loop.index == codes|length %}
                    </div>
                {% endif %}
            {% endfor %}
            
            
        </div>
        
        <h4>Project Documents</h4>
        
        <div class="row files">
        <div class="col-md-2 file" ><a href="#" class="file"><span class="fa fa-qrcode file-icon"></span><br>Stations</a></div>
        <div class="col-md-2 file" ><a href="{{ url_for('qrgenerator.generateConditionPDF') }}" class="file"><span class="fa fa-file-text-o file-icon"></span><br>Conditions</a></div>
        <div class="col-md-2 file" ><a href="#" class="file"><span class="fa fa-file-image-o file-icon"></span><br>Paper Form</a></div>
        <div class="col-md-2 file" ><a href="#" class="file"><span class="fa fa-file-excel-o file-icon"></span><br>Questionare</a></div>
        <div class="col-md-4"></div>
        </div>
        
		
		{% endblock %}

app/measurement/templates/person_detail.html
 {% extends "layout.html" %}
 
 
 
 
{% block content %}

{% for experimentName, experimentData in data %}
<h3>{{ experimentName }}</h3>
<div class="result-table">
  <table class="table table-hover">
    <thead>
      <tr>
        <th style="width: 30%;">Měření</th>
        <th style="width: 70%;">Výsledek</th>
      </tr>
    </thead>
    <tbody>
      
      {% for name, value, unit, type in experimentData %}
      <tr>
        <td style="width: 30%;">{{ name }}</td>
        <td style="width: 70%;">
            {% if type == 'checkbox' %} 
                {% for item in value %}
                    {% if item == 0 %}
                        <span class="glyphicon glyphicon-unchecked"></span>
                    {% elif item == 1 %}
                        <span class="glyphicon glyphicon-check"></span>
                    {% endif %}
                {% endfor %}
                
            {% else %} {{ value }} 
            {% endif %} 
            {{ unit }}</td><!--{{ value }} {{ unit }}</td>-->
      </tr>
      {% endfor %}
      
    </tbody>
  </table>
</div>

{% endfor %}


{% endblock %}

app/measurement/templates/planning.html
{% extends "layout.html" %}

		{% block title %}Measurement{% endblock %}
		{% block includes %}
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
            <link rel="stylesheet" href="{{ url_for('static', filename='popup.css') }}"> <!-- Resource style -->
            <link rel="stylesheet" href="{{ url_for('static', filename='table.css') }}"> <!-- Resource style -->
            <link rel="stylesheet" href="{{ url_for('static', filename='timeline.css') }}"> <!-- Resource style -->
            <link href="//code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" rel="Stylesheet">
            <script src="//code.jquery.com/jquery-2.2.0.min.js"></script>
            <script src="//code.jquery.com/ui/1.10.2/jquery-ui.js" ></script>
            <script src="{{ url_for('static', filename='js/show_div.js') }}"></script>
            <script type="text/javascript">
                $(document).ready( showForm );

                $(function() {
                    $("#experimentName").autocomplete({
                        source:function(request, response) {
                            $.getJSON("{{url_for('measurement.name_autocomplete')}}",{
                                qn: request.term, // in flask, "qn" will be the argument to look for using request.args
                            }, function(data) {
                                response(data.matching_results_n); // matching_results from jsonify
                            });
                        },
                        minLength: 1,
                        select: function(event, ui) {
                            console.log(ui.item.value);
                        }
                    });
                });

                $(function() {
                    $("#experimentExecutor").autocomplete({
                        source:function(request, response) {
                            $.getJSON("{{url_for('measurement.executor_autocomplete')}}",{
                                qe: request.term, // in flask, "qe" will be the argument to look for using request.args
                            }, function(data) {
                                response(data.matching_results_e); // matching_results from jsonify
                            });
                        },
                        minLength: 1,
                        select: function(event, ui) {
                            console.log(ui.item.value);
                        }
                    });
                });

            </script>
		{% endblock %}

		
		{% block content %}
		
		<div id="add_popup" class="overlay">
			<div class="popup">
				<h2 id="headline">Schedule a new measurement</h2>
				<a class="close" href="#" onclick="unloadAddPopup()">&times;</a>
				<div class="content">
					
					<form action="{{ url_for('measurement.planning_add') }}" method="post" id="form_add_plan">
                        <div class="before_next">
                            {{ form_add.hidden_tag() }}
                            {{ form_add.institution.label }}
                            {{ form_add.institution }} <br>
                            {{ form_add.begin.label }}
                            {{ form_add.begin(class='datepicker') }} <br>
                            {{ form_add.end.label }}
                            {{ form_add.end(class='datepicker') }} <br>
                            {{ form_add.town.label }}
                            {{ form_add.town }} <br>
                            {{ form_add.street.label }}
                            {{ form_add.street }} <br>
                            {{ form_add.number.label }}
                            {{ form_add.number }} <br>
                        	{{ form_add.add }}

                        </div>
					</form>
					<form action="{{ url_for('measurement.planning_add') }}" method="post" id="form_add_task">
                        <div class="after_next">
							{{ form_task.hidden_tag() }}
                            {{ form_task.experimentName.label }} <br>
                            {{ form_task.experimentName }}
                            <button type="button" class="show_table" id="showAllExperiments" onclick="showExperiments(1)">vše</button> <br>
                            {{ form_task.experimentExecutor.label }} <br>
                            {{ form_task.experimentExecutor }}
							{{ form_task.measurement_id(class='hidden') }}
                            <button type="button" class="show_table" id="showAllExperimenters" onclick="showExperiments(2)">vše</button> <br>
							<button type="submit"><i class="fa fa-plus-square-o"></i></button> <br>
                        </div>
                        <div class="show_all">
                            <table id="show_a">

                            </table>
                        </div>
					</form>
				</div>
                <div id="stateDiv">
                    <p id="stateP"></p>
                </div>
			</div>
		</div>
		

		<div id="edit_popup" class="overlay">
			<div class="popup">
				<h2>Upravit naplánované měření</h2>
				<a class="close" href="#" onclick="closeEdit()">&times;</a>
				<div class="content">
					
					<form action="{{ url_for('measurement.measure_planning') }}" method=post>
						{{ form_edit.hidden_tag() }}
						{{ form_edit.institution_e.label }}
						{{ form_edit.institution_e }} <br>
						{{ form_edit.begin_e.label }}
						{{ form_edit.begin_e }} <br>
						{{ form_edit.end_e.label }}
						{{ form_edit.end_e }} <br>
						{{ form_edit.town_e.label }}
						{{ form_edit.town_e }} <br>
						{{ form_edit.street_e.label }}
						{{ form_edit.street_e }} <br>
						{{ form_edit.number_e.label }}
						{{ form_edit.number_e }} <br>
						{{ form_edit.measure_id(class='hidden') }}
						{{ form_edit.edit }}
					</form>
				</div>
			</div>
		</div>
		
<section>
	<h1 class="page-header">Measurement Planning</h1>
	
	<ul class="timeline">
		<li>
			<a id="add_link" class="tm_new_measure" href="#">Add</a>
		</li>
		
		
		{% for d in data %}
		<li>
			<div class="tmicon"></div>
			<div class="tmlabel">
				<h2><a href="{{ url_for('measurement.planning_detail', id_measurement=d.id) }}">{{ d.institution }}</a></h2>
				<p>
					<span class="fa fa-calendar-o"> Date: </span>
                    <time class="date" datetime="2013-04-11T12:04">{{ d.begin.strftime('%d/%m/%y') }}</time><br>
                    <span class="fa fa-map-marker"> Place:</span> {{ d.town }} {{ d.street }} {{ d.number }}
					
				</p>
                <a href="#" class="label label-success"><span class="fa fa-qrcode"></span></a>
				<a href="#" onclick="showEdit({{ d.id }}, '{{ d.institution }}', '{{ d.town }}', '{{ d.street }}',
					'{{ d.number }}', '{{ d.begin }}', '{{ d.end }}')" title="Edit" class="label label-info"><span class="fa fa-pencil icon"></span></a>
				<a href="{{ url_for('measurement.remove_planned_measurement', id_remove=d.id) }}" title="Delete" class="label label-danger">
					<span class="fa fa-trash icon"></span></a>
			</div>
		</li>
		{% endfor %}
		
	</ul>

	</section> <!-- timeline -->
		
{% endblock %}

app/measurement/templates/project.html
{% macro link_to(endpoint, text) -%}
<a href="{{ url_for(endpoint, **kwargs) }}">{{ text|safe }}</a>
{%- endmacro %} 

{% extends "layout.html" %}

{% block content %}
<section>
	<h1 class="page-header">Body in Numbers</h1>
	<p>Unwillingness of many people to assume responsibilities for a personal health, fitness and wellness seems to be widespread. This can be partially remedied by individualized exercise and wellness program that integrates the basic knowledge domains: lifestyle, sports and fitness, and nutrition and personal/environmental health. However, collection, management and analysis of data and metadata related to these domains is demanding and time consuming task. Moreover, the appropriate annotation of raw data is crucial for their next processing. To promote such a~program a~software infrastructure for collection, storage, management, analysis and interpretation of health related data and metadata has been proposed and part of this infrastructure has been developed and tested outside laboratory conditions. This software prototype allows experimenters to collect various heterogeneous health related data in a~highly organized and efficient way. Data are then evaluated and users can view relevant information related to their health and fitness.</p>
</section>
{% endblock %}