app/equipment/models.py
from app import db


class Base(db.Model):
    """Base table"""
    __abstract__ = True

    id = db.Column(db.Integer, primary_key=True)
    date_created = db.Column(db.DateTime, default=db.func.current_timestamp())
    date_modified = db.Column(db.DateTime, default=db.func.current_timestamp(), onupdate=db.func.current_timestamp())


class EquipmentCategories(Base, db.Model):
    """Table with information about equipment categories"""
    __tablename__ = 'equipment_categories'

    categoryName = db.Column(db.String(64), nullable=False)


class MeasuringEquipment(Base, db.Model):
    """Table with information about measuring equipment and devices"""
    __tablename__ = 'measuring_equipment'

    deviceCategory = db.Column(db.Integer, db.ForeignKey(EquipmentCategories.id, onupdate="CASCADE", ondelete="CASCADE"))
    deviceName = db.Column(db.String(64), nullable=False)
    description = db.Column(db.String(256), nullable=True)

app/equipment/forms.py
from flask_wtf import Form
from wtforms import SubmitField, StringField, \
    TextAreaField, SelectField  # Import Form elements such as TextField and BooleanField (optional)
from wtforms.validators import DataRequired, length  # Import Form validators


class NewEquipmentForm(Form):
    """Form for adding new equipment"""
    deviceCategory = SelectField(u'Kategorie', coerce=int)
    deviceName = StringField('Název přístroje', [DataRequired(), length(max=64)])
    description = TextAreaField('Popis', [length(max=256)])
    add = SubmitField('Potvrdit')


class EditEquipmentForm(Form):
    """Form for edit equipment"""
    device_id = StringField('', [DataRequired()])
    deviceCategory_e = SelectField(u'Kategorie', coerce=int)
    deviceName_e = StringField('Název přístroje', [DataRequired(), length(max=64)])
    description_e = TextAreaField('Popis', [length(max=256)])
    edit = SubmitField('Uložit změny')


class AddCategoryForm(Form):
    """Form for adding categories"""
    categoryName = StringField('Název kategorie', [DataRequired(), length(max=64)])
    add = SubmitField('Vytvořit kategorii')

app/equipment/controllers.py
import jinja2
from flask import Blueprint, request, render_template, redirect
from app import db
from app.equipment.models import MeasuringEquipment, EquipmentCategories
from app.equipment.forms import NewEquipmentForm, EditEquipmentForm, AddCategoryForm
from flask_login import login_required

equipment = Blueprint('equipment', __name__, template_folder='templates', url_prefix='/app')


@equipment.route('/equipment/remove/<int:id_remove>')
@login_required
def remove_equipment(id_remove):
    """Remove selected equipment"""

    MeasuringEquipment.query.filter_by(id=id_remove).delete()
    db.session.commit()
    return redirect('app/equipment')


@equipment.route('/equipment/remove_cat/<int:id>')
@login_required
def remove_category(id):
    """Remove selected category"""

    EquipmentCategories.query.filter_by(id=id).delete()
    db.session.commit()
    return redirect('app/equipment')


@equipment.route('/equipment', methods=['GET', 'POST'])
@login_required
def get_equipment():
    """Adding equipments"""

    data = db.session.query(MeasuringEquipment).order_by(MeasuringEquipment.date_created.desc())
    cat = db.session.query(EquipmentCategories).order_by(EquipmentCategories.id)

    form_add = NewEquipmentForm(request.form)
    form_add.deviceCategory.choices = [(g.id, g.categoryName) for g in EquipmentCategories.query.order_by('id')]

    form_edit = EditEquipmentForm(request.form)
    form_edit.deviceCategory_e.choices = [(g.id, g.categoryName) for g in EquipmentCategories.query]

    form_cat = AddCategoryForm(request.form)
    
    if form_add.add.data and form_add.validate_on_submit():
        meas_eq_inst = MeasuringEquipment(
            deviceCategory=form_add.deviceCategory.data,
            deviceName=form_add.deviceName.data,
            description=form_add.description.data

            # created_by_user_id = 1
            # db.session.query(User).filter_by(id = currnet_user.get_id())
        )
        db.session.add(meas_eq_inst)
        db.session.commit()

    elif form_edit.edit.data and form_edit.validate_on_submit():
        equipment_inst = db.session.query(MeasuringEquipment).filter_by(id=form_edit.device_id.data).first()
        if equipment_inst:
            equipment_inst.deviceCategory = form_edit.deviceCategory_e.data
            equipment_inst.deviceName = form_edit.deviceName_e.data
            equipment_inst.description = form_edit.description_e.data
            db.session.flush()
            db.session.commit()

    elif form_cat.add.data and form_cat.validate_on_submit():
        meas_cat_inst = EquipmentCategories(
            categoryName=form_cat.categoryName.data
        )
        db.session.add(meas_cat_inst)
        db.session.commit()


    return render_template("equipment.html", title='Přístroj', data=data, cat=cat, form_add=form_add, form_edit=form_edit,
                           form_cat=form_cat)



#=====================================================================
@equipment.route('/equipment/add-category', methods=['GET', 'POST'])
@login_required
def add_category():
    """add new equipment category"""
    return render_template("add_category.html")
    
@equipment.route('/equipment/add-equipment', methods=['GET', 'POST'])
@login_required
def add_equipment():
    """add new equipment"""
    return render_template("add_equipment.html")

app/equipment/templates/equipment.html
{% extends "layout.html" %}

    {% block title %}Přístroje{% endblock %}
    {% block includes %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"
              xmlns="http://www.w3.org/1999/html">
        <link rel="stylesheet" href="{{ url_for('static', filename='popup.css') }}"> <!-- Resource style -->
        <link rel="stylesheet" href="{{ url_for('static', filename='table.css') }}"> <!-- Resource style -->
        <link rel="stylesheet" href="{{ url_for('static', filename='timeline.css') }}"> <!-- Resource style -->
        <script type=text/javascript src="{{ url_for('static', filename='js/jquery-3.1.0.js') }}"></script>
        <script src="{{ url_for('static', filename='js/show_div.js') }}"></script>
        <script type="text/javascript">
            $(document).ready( showForm );

            if (document.location.hash == "" || document.location.hash == "#")
                document.location.hash = "#tab1";

            $(document).ready(function () {
                var shift_h3 = 10;
                var shift_a = 115;
                {% for c in cat %}
                    shift_h3 = shift_h3 + 122;
                    $("article.tabs section:nth-child({{ loop.index + 1 }}) h3").css("left", shift_h3 + "px");
                    $("#del_cat{{ c.id }}").css("left", shift_a + "px");
                    shift_a = shift_a + 122;
                {% endfor %}
            });

        </script>
    {% endblock %}


    {% block content %}

    <div id="add_popup" class="overlay">
        <div class="popup">
            <h2>Nový přístroj</h2>
            <a class="close" href="#" onclick="unloadAddPopup()">&times;</a>
            <div class="content">

                <form action="{{ url_for('equipment.get_equipment') }}" method=post>
                    {{ form_add.hidden_tag() }}
                    {{ form_add.deviceCategory.label }}
                    {{ form_add.deviceCategory }} <br>
                    {{ form_add.deviceName.label }}
                    {{ form_add.deviceName }} <br>
                    {{ form_add.description.label }}
                    {{ form_add.description }} <br>
                    {{ form_add.add }}
                </form>
            </div>
        </div>
    </div>


    <div id="edit_popup" class="overlay">
        <div class="popup">
            <h2>Upravit informace o přístroji</h2>
            <a class="close" href="#" onclick="closeEdit()">&times;</a>
            <div class="content">

                <form action="{{ url_for('equipment.get_equipment') }}" method=post>
                    {{ form_edit.hidden_tag() }}
                    {{ form_edit.deviceCategory_e.label }}
                    {{ form_edit.deviceCategory_e }} <br>
                    {{ form_edit.deviceName_e.label }}
                    {{ form_edit.deviceName_e }} <br>
                    {{ form_edit.description_e.label }}
                    {{ form_edit.description_e }} <br>
                    {{ form_edit.device_id(class='hidden') }}
                    {{ form_edit.edit }}
                    <!--<input type="submit" value="edit"/>-->
                </form>
            </div>
        </div>
    </div>


    <div id="add_cat_popup" class="overlay">
        <div class="popup">
            <h2>Upravit informace o přístroji</h2>
            <a class="close" href="#" onclick="unloadAddCategory()">&times;</a>
            <div class="content">

                <form action="{{ url_for('equipment.get_equipment') }}" method=post>
                    {{ form_cat.hidden_tag() }}
                    {{ form_cat.categoryName.label }}
                    {{ form_cat.categoryName }} <br>
                    {{ form_cat.add }}
                </form>
            </div>
        </div>
    </div>

    <section>
        <h1 class="page-header">Equipment</h1>

        <a id="add_link" href="#" class="tm_new_equipment">Add new equipment</a> <br>

        <article class="tabs">

            {% for c in cat %}
            <section id="tab{{ loop.index }}" class="tabs_sec">
                <h3><a href="#tab{{ loop.index }}">{{ c.categoryName }}</a></h3>
                    <a class="add_category" href="#" onclick="loadAddCategory()">Add</a>
                    <a href="{{ url_for('equipment.remove_category', id=c.id) }}" id="del_cat{{ c.id }}" class="cancel_category"><span class="fa fa-close"></span></a>
                <table>
                    <tr>
                        <th>Equipment Name</th>
                        <th>Description</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                    {% for d in data %}
                        {% if d.deviceCategory == c.id %}
                        <tr>
                            <td>{{ d.deviceName }}</td>
                            <td>{{ d.description }}</td>
                            <td><a href="#" onclick="showEdit({{ d.id }}, {{ d.deviceCategory }}, '{{ d.deviceName }}', '{{ d.description }}')">
                                <span class="fa fa-pencil"></span></a></td>
                            <td><a href="{{ url_for('equipment.remove_equipment', id_remove=d.id) }}">
                                <span class="fa fa-trash"></span></a></td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                </table>
            </section>
            {% endfor %}
            <section id="tab{{ cat.count() + 1 }}" class="tabs_sec">
                <div class="tabs_a"><h3><a href="#tab{{ cat.count() + 1 }}">All</a></h3>
                <a class="add_category" href="#" onclick="loadAddCategory()">Add</a></div>
                <table>
                    <tr>
                        <th>Category</th>
                        <th>Equipment Name</th>
                        <th>Description</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                    {% for d in data %}
                        {% for c in cat %}
                            {% if d.deviceCategory == c.id %}
                            <tr>
                                <td>{{ c.categoryName }}</td>
                                <td>{{ d.deviceName }}</td>
                                <td>{{ d.description }}</td>
                                <td><a href="#" onclick="showEdit({{ d.id }}, {{ d.deviceCategory }}, '{{ d.deviceName }}', '{{ d.description }}')">
                                    <span class="fa fa-pencil"></span></a></td>
                                <td><a href="{{ url_for('equipment.remove_equipment', id_remove=d.id) }}">
                                    <span class="fa fa-trash"></span></a></td>
                            </tr>
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
                </table>
            </section>
        </article>



    </section>

{% endblock %}

app/equipment/templates/layout.html
{% macro link_to(endpoint, text) -%}
<a href="{{ url_for(endpoint, **kwargs) }}">{{ text|safe }}</a>
{%- endmacro %} 


<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>{% block title %}{% endblock %}</title>
		<link href='https://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="{{ url_for('static', filename='appstyle.css') }}"> <!-- Resource style -->
		{% block includes %}{% endblock %}
	</head>
	<body>
		<div>
			<header>Header
			
			</header>
			<nav>
				<div class="logo">Projektové dny</div>
				<h3>Navigation</h3>
				<ul class="menu">
					<li><a href="{{ url_for('measurement.project') }}" class="menu-item">Projekt</a></li>
					<li><a href="{{ url_for('measurement.measure_planning') }}" class="menu-item"><span class="i-active"></span>Měření</a></li>
					<ul class="menu">
						<li><a href="{{ url_for('measurement.measure_planning') }}" class="submenu-item">Plánování měření</a></li>
						<li><a href="{{ url_for('measurement.measured') }}" class="submenu-item">Proběhlá měření</a></li>
						<li><a href="{{ url_for('measurement.measured_persons') }}" class="submenu-item">Měřené osoby</a></li>
					</ul>
					<li><a href="{{ url_for('experiments.get_experiments') }}" class="menu-item">Experimenty</a></li>
                    <li><a href="{{ url_for('equipment.get_equipment') }}" class="menu-item">Přístroje</a></li>
					<li><a href="#" class="menu-item">Nastavení</a></li>
					<li><a href="{{ url_for('admin.show_all_users') }}" class="menu-item">Administrace</a></li>
				</ul>
				<div class="sidefooter"></div>
			</nav>
			<main>

				{% block content %}{% endblock %}

			</main>
			<aside>
				Aside Content Box</br>
				{{ link_to('auth.logout', "Logout") }}
			</aside>
			<footer>Footer Bar</footer>  
		</div>
	</body>
</html>