app/statistics/controllers.py
from flask import Blueprint, request, render_template, redirect, jsonify, abort, url_for
from app import app, db #, socketio
from app.measurement.models import Measurement, Measured_person, Measuring_station, Measured_values
from app.auth.models import User
from app.experiments.models import Experiments
from flask_login import login_required
from app.statistics.forms import CodeForm, StatisticsMeasurementForm
#from flask_socketio import SocketIO, emit
import json
from statistics import mean

statistics = Blueprint('statistics', __name__, template_folder='templates', url_prefix='') 

# změnit port
# registrace, co tam bude?
# 

@statistics.route('/show-results', methods=['GET', 'POST'])
@login_required
def showResultsForm():
    form = CodeForm(request.form)
    if form.validate_on_submit():
        #return url_for('showReactionTime')
        redirect('showResults', hexID=form.code.data)
    return render_template("result_form.html", form=form)

@statistics.route('/<string:hexID>')
@login_required
def showResults(hexID):
    """show table with client data"""
    person = Measured_person.getPersonByHexId(hexID)
    if not person:
        abort(404)
    data = Measured_values.getValues(person.id)


    experimentNames = []
    experimentsData = []
    for i, d in enumerate(data):
        names = []
        values = []
        units = []
        ex = Experiments.getExperiment(d.data_from_experiment)
        #print(json.dumps(ex.experimentScheme, ensure_ascii=False))
        scheme = ex.experimentScheme
        jsondata = d.data
        #print(json.dumps(d.data))
        #print(ex.experimentName)
        print(".....")
        print(d.data_from_experiment)
        f = json.dumps(d.data)
        experimentNames.append(ex.experimentName)
        
        for index, v in enumerate(jsondata):
            #if scheme[index]["formType"] == "radio" and v["values"][0]:
            if scheme[int(v["id"])]["formType"] == "radio" and v["values"][0]:
                #print(int(v["values"][0]))
                values.append(scheme[int(v["id"])]["formLabels"][int(v["values"][0])])
                #values.append(scheme[index]["formLabels"][int(v["values"][0])])
            else:
                values.append(v["values"][0])
            #units.append(scheme[index]["units"])
            units.append(scheme[int(v["id"])]["units"])
            #names.append(scheme[index]["name"])
            names.append(scheme[int(v["id"])]["name"])
            print("=======")
            print(int(v["id"]))
            #print(scheme[int(v["id"])]["name"])

        experimentsData.append(zip(names, values, units))
        #break
    #return render_template("results.html", person_id=hexID, data=zip(names, values, units))
    return render_template("results.html", person_id=hexID, data=zip(experimentNames, experimentsData))

@statistics.route('/all')
@login_required
def showAllResults():
    data = Measured_values.getAllValues()
    j = data[6].data
    names = []
    values = []
    units = []
    experimentNames = []
    for i, d in enumerate(data):
        ex = Experiments.getExperiment(d.data_from_experiment)
        print(json.dumps(ex.experimentScheme))
        scheme = ex.experimentScheme
        jsondata = d.data
        print(ex.experimentName)
        f = json.dumps(d.data)
        experimentNames.append(ex.experimentName)
        if i is 6:
            print(jsondata[0]["values"])
            for index, v in enumerate(jsondata):
                
                values.append(v["values"][0])
                units.append(scheme[index]["units"])
                names.append(scheme[index]["name"])
    return render_template("allresults.html", data=zip(names, values, units))

@statistics.route('/reaction-time2')
@login_required
def showReactionTime2():
    """Shows page with charts"""
    menHands = []
    menHandIDs = []
    womenHands = []
    womenHandIDs = []
    menLegs = []
    menLegIDs = []
    womenLegs = []
    womenLegIDs = []
    
    #expHands = Experiments.getExperimentByName("Reakční doba horních končetin")[0]         ###
    #expLegs = Experiments.getExperimentByName("Reakční doba horních končetin")         ###
    #expReg = Experiments.getExperimentByName("Registrace")         ###
    
    expHands = 5
    expLegs = 6
    expReg = 1
    
    valHands = Measured_values.getValuesByExperiment(expHands)
    valLegs = Measured_values.getValuesByExperiment(expLegs)

    aaa = 0
    bbb = "dvgr"
    
    for v in valHands:
        reg = Measured_values.getRegistration(v.measured_person_id, expReg)
        hashID = Measured_person.getPersonById(reg.measured_person_id)
        if v.data[0]["values"][0]:
            #if pohlavi zena nebo muz           ###
            if reg.data[0]["values"][0] == "0":
                womenHandIDs.append(hashID.personHash)
                womenHands.append(int(v.data[0]["values"][0]))
            else:
                menHandIDs.append(hashID.personHash)
                menHands.append(int(v.data[0]["values"][0]))
            
    for v in valLegs:
        reg = Measured_values.getRegistration(v.measured_person_id, expReg)
        hashID = Measured_person.getPersonById(reg.measured_person_id)
        if v.data[0]["values"][0]:
            if reg.data[0]["values"][0] == "0":
                womenLegIDs.append(hashID.personHash)
                womenLegs.append(int(v.data[0]["values"][0]))
            else:
                menLegIDs.append(hashID.personHash)
                menLegs.append(int(v.data[0]["values"][0]))
        
    
    menHands, menHandIDs = (list(t) for t in zip(*sorted(zip(menHands, menHandIDs))))###
    womenHands, womenHandIDs = (list(t) for t in zip(*sorted(zip(womenHands, womenHandIDs))))###
    
    menLegs, menLegIDs = (list(t) for t in zip(*sorted(zip(menLegs, menLegIDs))))###
    womenLegs, womenLegIDs = (list(t) for t in zip(*sorted(zip(womenLegs, womenLegIDs))))###
    
    
    womenHandsSort = sorted(womenHands)
    menHandsSort = sorted(menHands)
    womenLegsSort = sorted(womenLegs)
    menLegsSort = sorted(menLegs)
    
    num = range(1, 6)
    
    
    menHandsZip = zip(num, menHandIDs[:5], menHandsSort[:5])
    womenHandsZip = zip(num, womenHandIDs[:5], womenHandsSort[:5])
    menLegsZip = zip(num, menLegIDs[:5], menLegsSort[:5])
    womenLegsZip = zip(num, womenLegIDs[:5], womenLegsSort[:5])
    
    avgHandMen = sum(menHands)/float(len(menHands))
    avgHandWomen = sum(womenHands)/float(len(womenHands))
    avgLegMen = sum(menLegs)/float(len(menLegs))
    avgLegWomen = sum(womenLegs)/float(len(womenLegs))
    
    return render_template("reaction_time2.html", menHandsZip=menHandsZip, menLegsZip=menLegsZip, womenHandsZip=womenHandsZip, womenLegsZip=womenLegsZip, avgHandMen=avgHandMen, avgHandWomen=avgHandWomen, avgLegWomen=avgLegWomen, avgLegMen=avgLegMen, menCount=len(menLegIDs), womenCount=len(womenLegIDs))
    

@statistics.route('/summary-statistics', methods=['GET', 'POST'])
@login_required
def showSummaryStatistics():
    """Reports and summary statistics"""
    
    statisticsForm = StatisticsMeasurementForm(request.form)
    if statisticsForm.data and statisticsForm.validate_on_submit():
    #provizorni presmerovani
        if statisticsForm.hands.data:
            return redirect(url_for('statistics.showReactionTime', measurement=statisticsForm.measurement.data))
        elif statisticsForm.legs.data:
            return redirect(url_for('statistics.showReactionTime', measurement=statisticsForm.measurement.data))
        
    return render_template("summary_statistics.html", form=statisticsForm)

@statistics.route('/reaction-time/<int:measurement>', methods=['GET', 'POST'])
@login_required
def showReactionTime(measurement):
    """Shows page with charts"""
    
    #measurement = Measurement.getMeasurementByName("reakce")
    #measurementID = measurement.id
    measurementID = measurement
    valHands = Measured_values.getValuesForHandsReactions(measurementID)
    valLegs = Measured_values.getValuesForLegsReactions(measurementID)
    expReg = Experiments.getExperimentByName("Registrace")
    handsReactions = []
    handsPersonIDs = []
    handsSex = []
    handsAge = []
    legsReactions = []
    legsPersonIDs = []
    legsSex = []
    legsAge = []
    
    handsDecadeSum = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    legsDecadeSum = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    handsDecadeCount = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    legsDecadeCount = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    
    for val in valHands:
        for reaction in val.data:
            if reaction["id"] == 0:
                handsReactions.append(reaction["values"][0])
                person = Measured_person.getPersonById(val.measured_person_id)
                handsPersonIDs.append(person.personHash)
                reg = Measured_values.getRegistration(val.measured_person_id, expReg.id)
                for r in reg.data:
                    if r["id"] == 0:
                        handsSex.append(r["values"][0])
                    if r["id"] == 1:
                        handsAge.append(r["values"][0])
                        decade = int(r["values"][0] / 10)
                        if decade > 9:
                            decade = 9
                        handsDecadeSum[decade] += reaction["values"][0]
                        handsDecadeCount[decade] += 1
                break
                
    for val in valLegs:
        for reaction in val.data:
            if reaction["id"] == 0:
                legsReactions.append(reaction["values"][0])
                person = Measured_person.getPersonById(val.measured_person_id)
                legsPersonIDs.append(person.personHash)
                reg = Measured_values.getRegistration(val.measured_person_id, expReg.id)
                for r in reg.data:
                    if r["id"] == 0:
                        legsSex.append(r["values"][0])
                    if r["id"] == 1:
                        legsAge.append(r["values"][0])

app/statistics/templates/allresults.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">


    <title>Static Top Navbar Example for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.css') }}"> <!-- Resource style -->

    <style>
    .result-table {
            padding: 1em;
            border-radius: 10px;
    }
    
    .content {
            background-color: white;
    }
    
    body {
            background-color: #F6F6F6;
    }
    </style>

  </head>

  <body>

    <!-- Static navbar -->
    <nav class="navbar navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Logo - Lenochod</a>
          
          <h4 class="navbar-text">Výsledek Měření</h4> 
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    <div class="container">

    {% for name, value, unit in data %}
    {{ name }} - {{ value }} - {{ unit }}
    </br>
    {% endfor %}

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
  </body>
</html>
 

app/statistics/templates/menu2.html
{% extends "layout.html" %}

{% block title %}Naměřené osoby{% endblock %}
{% block includes %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename='popup.css') }}"> <!-- Resource style -->
<link rel="stylesheet" href="{{ url_for('static', filename='table.css') }}"> <!-- Resource style -->

<style>
.nav-tabs>.active>a, .nav-tabs>.active>a:hover, .nav-tabs>.active>a:focus {
    border-color: #57a5bf;
    border-bottom-color: transparent;
}
    
.nav-tabs{
  border-bottom: 2px solid #57a5bf;
}

.tab-content{
    background-color:#57a5bf;
    color:#fff;
}

.nav-tabs > .active > a {
border-bottom: none;
position: relative;
top: 2px;

    /* works with 1px */
}

.nav-tabs > li.active > a, .nav-tabs > li.active > a:focus, .nav-tabs > li.active > a:hover { 
    background-color: #fff; 
    cursor: default;
    border-color: #57a5bf;
    border-width: 2px;
    border-bottom-color: transparent;
}


</style>

{% endblock %}

{% block content %}
<ul class="nav nav-tabs">
    <li><a data-toggle="tab" href="{{ url_for('statistics.showSummaryStatistics') }}">Summary</a></li>
    <li class="active"><a data-toggle="tab" href="{{ url_for('statistics.showReactionTime') }}" >Reaction Time</a></li>
    <li><a data-toggle="tab" href="#menu2" >Heart</a></li>
    <li><a data-toggle="tab" href="#menu3" >Fitness</a></li>
  </ul>


<section class="content">


<p>statistika</p>
</section>
{% endblock %}

app/statistics/templates/reaction_time.html
{% extends "layout.html" %}

{% block title %}Naměřené osoby{% endblock %}
{% block includes %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename='popup.css') }}"> <!-- Resource style -->
<link rel="stylesheet" href="{{ url_for('static', filename='table.css') }}"> <!-- Resource style -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<style>
.nav-tabs>.active>a, .nav-tabs>.active>a:hover, .nav-tabs>.active>a:focus {
    border-color: #57a5bf;
    border-bottom-color: transparent;
}
    
.nav-tabs{
  border-bottom: 2px solid #57a5bf;
}

.tab-content{
    background-color:#57a5bf;
    color:#fff;
}

.nav-tabs > .active > a {
border-bottom: none;
position: relative;
top: 2px;

    /* works with 1px */
}

.nav-tabs > li.active > a, .nav-tabs > li.active > a:focus, .nav-tabs > li.active > a:hover { 
    background-color: #fff; 
    cursor: default;
    border-color: #57a5bf;
    border-width: 2px;
    border-bottom-color: transparent;
}

/* responsive canvas */
canvas {
  width: 100%;
  height: auto;
}

/************* reactions ***************/
.man {
  color: #3e95cd;
  font-weight: bold;
}

.woman {
  color: #e60000;  
  font-weight: bold;
}

.id-style {
    font-weight: bold;
}

</style>

{% endblock %}

{% block content %}
<!--<ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="{{ url_for('statistics.showSummaryStatistics') }}">Summary</a></li>
    <li><a data-toggle="tab" href="#" >Reaction Time</a></li>
    <li><a data-toggle="tab" href="#menu2" >Heart</a></li>
    <li><a data-toggle="tab" href="#menu3" >Fitness</a></li>
  </ul>-->
  
  


<section class="content">




<div class="row">
    <div class="col-md-6">
            <h2 style="background-color: #00cc99; color: white; padding-top: 0.2em; padding-bottom: 0.2em; padding-left: 0.8em;">Hands Reaction Time</h2>
            <canvas id="hands-avg-time" width="800" height="300">Sorry, your browser doesn't support the &lt;canvas&gt; element.</canvas>
        
    </div> <!-- /col-md-6 -->
    <div class="col-md-6">
        
        <h2 style="background-color: #3e95cd;  color: white; padding-top: 0.2em; padding-bottom: 0.2em; padding-left: 0.8em;" >Legs Reaction Time</h2>
        <canvas id="legs-avg-time" width="800" height="300">Sorry, your browser doesn't support the &lt;canvas&gt; element.</canvas>
        
    </div> <!-- /col-md-6 -->
</div> <!-- /row -->




<div class="row">
    <div class="col-md-6">
        
        
        
          <table class="table">
            <thead>
              <tr>
                <th>Position</th>
                <th>ID</th>
                <th>Time</th>
                <th>Sex</th>
                <th>Decade</th>
              </tr>
            </thead>
            <tbody>
                
            {% for hands, personID, sex in handsZip %}
              <tr>
                <td>{{ loop.index }}.</td>
                <td class="id-style">{{ personID }}</td>
                <td>{{ hands }} ms</td>
                <td>
                    {% if sex == 0 %}
                    <span class="man fa fa-mars">
                    {% elif sex == 1 %}
                    <span class="woman fa fa-venus">
                    {% endif %}
                    </span></td>
                
                <td>-</td>
              </tr>
              
              {% endfor %}

            </tbody>
          </table>
        
        
    </div> <!-- /col-md-6 -->
    <div class="col-md-6">
        
        
        
          <table class="table">
            <thead>
              <tr>
                <th>Position</th>
                <th>ID</th>
                <th>Time</th>
                <th>Sex</th>
                <th>Decade</th>
              </tr>
            </thead>
            <tbody>
            {% for legs, personID, sex in legsZip %}
              <tr>
                <td>{{ loop.index }}.</td>
                
                <td class="id-style">{{ personID }}</td>
                <td>{{ legs }} ms</td>
                <td>
                    {% if sex == 0 %}
                    <span class="man fa fa-mars">
                    {% elif sex == 1 %}
                    <span class="woman fa fa-venus">
                    {% endif %}
                    </span></td>
                
                <td>-</td>
              </tr>
            {% endfor %}

            </tbody>
          </table>
        
    </div> <!-- /col-md-6 -->
</div> <!-- /row -->



<!-- Age Decades -->
<div class="row">
    <div class="col-md-6">
        
          
    <canvas id="hands-chart" width="800" height="400">Sorry, your browser doesn't support the &lt;canvas&gt; element.</canvas>
        
        
    </div> <!-- /col-md-6 -->
    <div class="col-md-6">
        
        
        <canvas id="legs-chart" width="800" height="400">Sorry, your browser doesn't support the &lt;canvas&gt; element.</canvas>
        
    </div> <!-- /col-md-6 -->
</div> <!-- /row -->


<!-- Histograms -->
<div class="row">
    <div class="col-md-6">
        
          
    <canvas id="histogram-hands" width="800" height="400">Sorry, your browser doesn't support the &lt;canvas&gt; element.</canvas>
        
        
    </div> <!-- /col-md-6 -->
    <div class="col-md-6">
        
        
        <canvas id="histogram-legs" width="800" height="400">Sorry, your browser doesn't support the &lt;canvas&gt; element.</canvas>
        
    </div> <!-- /col-md-6 -->
</div> <!-- /row -->

<script>


// Bar chart hands
new Chart(document.getElementById("hands-chart"), {
    type: 'bar',
    data: {
      labels: ["0-9", "10-19", "20-29", "30-39", "40-49", "50-59", "60-69", "70-79", "80-89", "90-99"],
      datasets: [
        {
          label: "Population (millions)",
          backgroundColor: ['#a50026','#d73027','#f46d43','#fdae61','#fee08b','#d9ef8b','#a6d96a','#66bd63','#1a9850','#006837'],
          data: {{ handsDecades }}
        }
      ]
    },
    options: {
      legend: { display: false },
      title: {
        display: true,
        text: 'Reaction Time - Hands'
      },
          scales: {
    yAxes: [{
      scaleLabel: {
        display: true,
        labelString: 'Reactions [ms]'
      }
    }],
    
    xAxes: [{
      scaleLabel: {
        display: true,
        labelString: 'Age'
      }
    }]
  }  
    }
});


// Bar chart legs
new Chart(document.getElementById("legs-chart"), {
    type: 'bar',
    data: {
      labels: ["0-9", "10-19", "20-29", "30-39", "40-49", "50-59", "60-69", "70-79", "80-89", "90-99"],
      datasets: [
        {
          label: "Population (millions)",
          backgroundColor: ['#9e0142','#d53e4f','#f46d43','#fdae61','#fee08b','#e6f598','#abdda4','#66c2a5','#3288bd','#5e4fa2'],
          data: {{ legsDecades }}
        }
      ]
    },
    options: {
      legend: { display: false },
      title: {
        display: true,
        text: 'Reaction Time - Legs'
      },
                scales: {
    yAxes: [{
      scaleLabel: {
        display: true,
        labelString: 'Reactions [ms]'
      }
    }],
    
    xAxes: [{
      scaleLabel: {
        display: true,
        labelString: 'Age'
      }
    }]
  } 
    }
});




// Hands avg time
new Chart(document.getElementById("hands-avg-time"), {
    type: 'doughnut',
    data: {
      labels: ["Hands average"],
      datasets: [
        {
          label: "Population (millions)",
          backgroundColor: ["#00cc99"],
          data: [{{ handsMean }},100]
        }
      ]
    },
    options: {
      title: {
        display: false
      },
      legend: {
        display: false
      },
      cutoutPercentage: 70
    }
    
});

// Legs avg time
new Chart(document.getElementById("legs-avg-time"), {
    type: 'doughnut',
    data: {
      labels: ["Legs average"],
      datasets: [
        {
          label: "Population (millions)",
          backgroundColor: ["#3e95cd"],
          data: [{{ legsMean }},100]
        }
      ]
    },
    options: {
      title: {
        display: false
      },
      legend: {
        display: false
      },
      cutoutPercentage: 70
    }
});




Chart.pluginService.register({
  beforeDraw: function(chart) {
    var width = chart.chart.width,
        height = chart.chart.height,
        ctx = chart.chart.ctx,
        type = chart.config.type;

    if (type == 'doughnut')
    {
    	/*var percent = Math.round((chart.config.data.datasets[0].data[0] * 100) / (chart.config.data.datasets[0].data[0] + chart.config.data.datasets[0].data[1]));*/
        var value = chart.config.data.datasets[0].data[0];
        var oldFill = ctx.fillStyle;
        var fontSize = ((height - chart.chartArea.top) / 100).toFixed(2);
      
      ctx.restore();
      ctx.font = fontSize + "em sans-serif";
      ctx.textBaseline = "middle"

      var name = "AVG", nameX = Math.round((width - ctx.measureText(name).width) / 2), nameY = (height + chart.chartArea.top) / 2.3;

      var text = value + "" + " ms",
          textX = Math.round((width - ctx.measureText(text).width) / 2),
          textY = (height + chart.chartArea.top) / 1.7;
			
      ctx.fillStyle = chart.config.data.datasets[0].backgroundColor[0];
      ctx.fillText(text, textX, textY);
      ctx.fillText(name, nameX, nameY);
      ctx.fillStyle = oldFill;
      ctx.save();
    }
  }
});


// histogram hands
new Chart(document.getElementById("histogram-hands"), {
  type: 'line',
  data: {
    labels: {{ histLabels }},
    datasets: [{ 
        data: {{ histHands }},
        label: "North America",
        borderColor: "#00cc99",
        fill: "true",
        backgroundColor : "#ccfff2"
      }
    ]
  },
  options: {
    title: {
      display: true,
      text: 'Histogram - hands'
    },
    legend: {
        display: false
    },
    elements: {
      point:{
        radius: 0
      }
    },
    scales: {
    yAxes: [{
      scaleLabel: {
        display: true,
        labelString: 'Frequency'
      }
    }],
    
    xAxes: [{
      scaleLabel: {
        display: true,
        labelString: 'Reactions [ms]'
      }
    }]
  }     
  }
});


// histogram legs
new Chart(document.getElementById("histogram-legs"), {
  type: 'line',
  data: {
    labels: {{ histLabels }},
    datasets: [{ 
        data: {{ histLegs }},
        label: "Amount",
        borderColor: "#3e95cd",
        fill: "true",
        backgroundColor : "#c2deef"
      }
    ]
  },
  options: {
    title: {
      display: true,
      text: 'Histogram - legs'
    },
    legend: {
        display: false
    },
    elements: {
      point:{
        radius: 0
      }
    },
    scales: {
    yAxes: [{
      scaleLabel: {
        display: true,
        labelString: 'Frequency'
      }
    }],
    
    xAxes: [{
      scaleLabel: {
        display: true,
        labelString: 'Reactions [ms]'
      }
    }]
  }     
  }
});

</script>


</section>
{% endblock %}

app/statistics/templates/result_form.html
{% extends "web-layout.html" %} 



{% block includes %}{% endblock %} 


{% block content %}


    <div class="first-page" style="height: 100%;">
        <form action="{{ url_for('statistics.showResultsForm') }}" method=post class="text-center">
            {{ form.code(class_="blue-input") }}
            {{ form.hidden_tag() }}
            <input type="submit" value="Get Info" class="btn blue-button blue-button-fix">
        </form>	
    </div>

{% endblock %}