app/equipment/controllers.py
import jinja2
from flask import Blueprint, request, render_template, redirect
from app import db
from app.equipment.models import MeasuringEquipment, EquipmentCategories
from app.equipment.forms import NewEquipmentForm, EditEquipmentForm, AddCategoryForm
from flask_login import login_required

equipment = Blueprint('equipment', __name__, template_folder='templates', url_prefix='/app')


@equipment.route('/equipment/remove/<int:id_remove>')
@login_required
def remove_equipment(id_remove):
    """Remove selected equipment"""

    MeasuringEquipment.query.filter_by(id=id_remove).delete()
    db.session.commit()
    return redirect('app/equipment')


@equipment.route('/equipment/remove_cat/<int:id>')
@login_required
def remove_category(id):
    """Remove selected category"""

    EquipmentCategories.query.filter_by(id=id).delete()
    db.session.commit()
    return redirect('app/equipment')


@equipment.route('/equipment', methods=['GET', 'POST'])
@login_required
def get_equipment():
    """Adding equipments"""

    data = db.session.query(MeasuringEquipment).order_by(MeasuringEquipment.date_created.desc())
    cat = db.session.query(EquipmentCategories).order_by(EquipmentCategories.id)

    form_add = NewEquipmentForm(request.form)
    form_add.deviceCategory.choices = [(g.id, g.categoryName) for g in EquipmentCategories.query.order_by('id')]

    form_edit = EditEquipmentForm(request.form)
    form_edit.deviceCategory_e.choices = [(g.id, g.categoryName) for g in EquipmentCategories.query]

    form_cat = AddCategoryForm(request.form)
    
    if form_add.add.data and form_add.validate_on_submit():
        meas_eq_inst = MeasuringEquipment(
            deviceCategory=form_add.deviceCategory.data,
            deviceName=form_add.deviceName.data,
            description=form_add.description.data

            # created_by_user_id = 1
            # db.session.query(User).filter_by(id = currnet_user.get_id())
        )
        db.session.add(meas_eq_inst)
        db.session.commit()

    elif form_edit.edit.data and form_edit.validate_on_submit():
        equipment_inst = db.session.query(MeasuringEquipment).filter_by(id=form_edit.device_id.data).first()
        if equipment_inst:
            equipment_inst.deviceCategory = form_edit.deviceCategory_e.data
            equipment_inst.deviceName = form_edit.deviceName_e.data
            equipment_inst.description = form_edit.description_e.data
            db.session.flush()
            db.session.commit()

    elif form_cat.add.data and form_cat.validate_on_submit():
        meas_cat_inst = EquipmentCategories(
            categoryName=form_cat.categoryName.data
        )
        db.session.add(meas_cat_inst)
        db.session.commit()


    return render_template("equipment.html", title='Přístroj', data=data, cat=cat, form_add=form_add, form_edit=form_edit,
                           form_cat=form_cat)



#=====================================================================
@equipment.route('/equipment/add-category', methods=['GET', 'POST'])
@login_required
def add_category():
    """add new equipment category"""
    return render_template("add_category.html")
    
@equipment.route('/equipment/add-equipment', methods=['GET', 'POST'])
@login_required
def add_equipment():
    """add new equipment"""
    return render_template("add_equipment.html")

app/fitness/controllers.py
from flask import Blueprint, request, render_template, redirect, jsonify, abort, url_for
from app import app, db
from app.auth.models import create_data
from app.admin.controllers import show_all_users
from flask_login import login_required
from app.fitness.forms import FoodForm
from app.fitness.food.models import DaySettings, FoodDefinition, FoodTracking, Food
from app.fitness.exercise.models import ExerciseTracking, Exercise, ExerciseType
from flask_login import current_user
from werkzeug.routing import Rule
import csv
import io

from app.fitness.forms import FoodForm
import json

fitness = Blueprint('fitness', __name__, template_folder='templates', url_prefix='/app')

@fitness.route('/fitness/food', methods=['GET', 'POST'])
def showFood():
    """Sample blank page"""
    # wtforms
    foodForm = FoodForm()
    if foodForm.data['foodInput']:
        parseFile(foodForm.data['foodInput'])
    if foodForm.data['exerciseInput']:
        parseExerciseFile(foodForm.data['exerciseInput'])
    return render_template("food.html", form=foodForm)

@fitness.route('/fitness/food/generate', methods=['GET', 'POST'])
def genData():
    fillByTestData()
    print("Vygenerovano")
    return redirect('/app/fitness/food')

def parseFile(csv_file):
    """Parse CSV file"""
    buffer = io.StringIO(csv_file.stream.read().decode("UTF8"), newline=None)
    csv_data = csv.reader(buffer, delimiter=',')

    for index, row in enumerate(csv_data):
        if (index == 0):
            continue
        print(row[0])

        Food.add_food(row[0], row[1], row[2], row[3], row[4], row[5])

def parseExerciseFile(csv_file):
    """Parse CSV file"""
    buffer = io.StringIO(csv_file.stream.read().decode("UTF8"), newline=None)
    csv_data = csv.reader(buffer, delimiter=',')
    type = ExerciseType.add_exercise_type("cvik", 0)

    for index, row in enumerate(csv_data):
        if (index == 0):
            continue
        print(row[0])

        Exercise.add_exercise(row[0], type, 0)

def fillByTestData():

    user_id = current_user.get_id()
    DaySettings.add_settings(DaySettings, user_id, 90, 2500, 2)

    f_1 = FoodTracking.add_foodtracking(user_id, 0)
    f_2 = FoodTracking.add_foodtracking(user_id, 0)
    f_3 = FoodTracking.add_foodtracking(user_id, 0)
    f_4 = FoodTracking.add_foodtracking(user_id, 0)

    FoodDefinition.add_definition(f_1, 'Jidlo_test', 100, 300, 1, 20, 20, 100)
    FoodDefinition.add_definition(f_2, 'Jidlo_test1', 130, 100, 0.2, 10, 5, 100)
    FoodDefinition.add_definition(f_3, 'Jidlo_test2', 0.30, 200, 0.1, 5, 11, 100)

    FoodDefinition.add_definition(f_4, 'Jidlo_test_a', 100, 300, 1, 20, 20, 100)
    FoodDefinition.add_definition(f_4, 'Jidlo_test_b', 130, 100, 0.2, 10, 5, 100)
    FoodDefinition.add_definition(f_4, 'Jidlo_test_c', 30, 200, 0.1, 5, 11, 100)

    f_a = ExerciseType.add_exercise_type("typ1", 0)
    f_b = ExerciseType.add_exercise_type("typ2", 0)

    f_1 = Exercise.add_exercise("klik", f_a, 0)
    f_2 = Exercise.add_exercise("klik1", f_b, 0)
    f_3 = Exercise.add_exercise("klik2", f_a, 0)
    f_4 = Exercise.add_exercise("klik3", f_b, 0)
    f_5 = Exercise.add_exercise("klik4", f_b, 0)
    f_6 = Exercise.add_exercise("klik5", f_b, 0)
    f_7 = Exercise.add_exercise("drep1", f_b, 0)
    f_8 = Exercise.add_exercise("drep2", f_b, 0)
    f_9 = Exercise.add_exercise("drep3", f_b, 0)
    f_10 = Exercise.add_exercise("drep4", f_b, 0)
    f_11 = Exercise.add_exercise("drep5", f_b, 0)

    ExerciseTracking.add_tracking(user_id, f_1, 600)
    ExerciseTracking.add_tracking(user_id, f_1, 600)
    ExerciseTracking.add_tracking(user_id, f_1, 600)

    ExerciseTracking.add_tracking(user_id, f_1, 300)
    ExerciseTracking.add_tracking(user_id, f_2, 200)
    ExerciseTracking.add_tracking(user_id, f_2, 100)

app/general/controllers.py
from app import app, bcrypt
from app import db
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from flask_wtf import form
from flask_login import login_user, logout_user, login_required, current_user
from app.auth.models import User,Role, roles_users
from app.measurement.models import Measured_person
from app.general.forms import ChangePassword, ChangeAvatar
#from werkzeug import security
from flask_bcrypt import Bcrypt, check_password_hash, generate_password_hash


general = Blueprint('general', __name__, template_folder='templates')

@general.route('/')
def to_index():
    return redirect('index')
    

@general.route('/index')
def index():
    """Main page"""
    personNumber = Measured_person.countPersons()
    return render_template("home.html", personNumber=personNumber)

@general.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    """User profile - show permissions, can add photo, his statistics, password change"""

    roles = ""
    index = 0
    for r in current_user.roles:
        if index != 0:
            roles += ", "
        roles += r.name
        ++index

    min_lenght = 8
    form_change = ChangePassword(request.form)
    form_avatar = ChangeAvatar(request.form)

    if form_change.change.data and form_change.validate_on_submit():
        if bcrypt.check_password_hash(current_user.password, form_change.oldPassword.data):
            if form_change.newPassword.data == form_change.newPasswordRepeat.data:
                if len(form_change.newPassword.data) >= min_lenght:
                    user_inst = db.session.query(User).filter_by(id=current_user.id).first()
                    passwd = form_change.newPassword.data
                    passwd.encode('utf-8')
                    pwd = bcrypt.generate_password_hash(passwd).decode('utf8')
                    user_inst.password = pwd
                    db.session.flush()
                    db.session.commit()
                    flash("Heslo bylo změněno!")
                else:
                    flash("Nové heslo je příliš krátké. Musí mít minimálně {} znaků.".format(min_lenght))
            else:
                flash("Hesla se neshodují")
        else:
            flash("Vaše aktuální heslo bylo zadáno špatně!")

    """if form_avatar.validate_on_submit():
        filename = secure_filename(form_avatar.file.data.filename)
        form_avatar.file.data.save('uploads/' + filename)
        flash("Profilový obrazek byl změněn")"""


    return render_template("profile.html", current_user = current_user, roles = roles, form_change = form_change, form_avatar= form_avatar)

app/templates/base.html
{% macro link_to(endpoint, text) -%}
<a href="{{ url_for(endpoint, **kwargs) }}">{{ text|safe }}</a>
{%- endmacro %}

<html>
	<head>
		{% if title %}
		<title>{{ title }} - microblog</title>
		{% else %}
		<title>Zdravý lenochod</title>
		{% endif %}
	</head>
	<body>
		{% block content %}{% endblock %}
	</body>
</html>

app/templates/forgot.html
<html>
  <head>
    <title></title>
    <meta content="">
    <style></style>
  </head>
  <body></body>
</html>

app/templates/layout.html
{% macro link_to(endpoint, text) -%}
<a href="{{ url_for(endpoint, **kwargs) }}">{{ text|safe }}</a>
{%- endmacro %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{{ url_for('static', filename='img/favicon.png') }}">
      
      
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <title>Body in Numbers</title>
    
    <link href='https://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>

    <!-- Bootstrap core CSS -->
    <!--<link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">-->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{{ url_for('static', filename='layout-style.css') }}"> <!-- Resource style -->


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    {% block includes %}{% endblock %} 
  </head>

  <body>


    <nav class="navbar navbar-default navbar-fixed-top my-color navbar-custom">
      <div class="container-fluid">
        <div class="navbar-header">

        <a class="navbar-brand menu-text-color" href="{{ url_for('measurement.project') }}"><img src="{{ url_for('static', filename='img/lenochod.png') }}" alt="Lenochod" style="width:20px;height:20px;"></a>
        </div>
        
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <!--<li><a href="#"><img src="foto.jpeg" alt="Lenochod" style="width:25px;height:25px;" class="img-circle"></a></li>-->
            <li><a href="{{ url_for('auth.logout') }}" ><span class="fa fa-user"></span>  Logout</a></li>
            <li><a onclick="openNav()" href="javascript:void(0)"><span class="glyphicon glyphicon-cog"></span></a></li>

          </ul>
          
          <ul class="nav navbar-nav navbar-left">
            <li><a href="{{ url_for('measurement.go_measure') }}"><span class="fa fa-stethoscope"></span> Go measure</a></li>
            <li><a href="{{ url_for('measurement.measure_planning') }}"><span class="fa fa-calendar-o"></span> Planning</a></li>
            <li><a href="{{ url_for('measurement.show_all_projects') }}"><span class="fa fa-folder-open-o"></span> Data</a></li>
            <li><a href="{{ url_for('statistics.showSummaryStatistics') }}"><span class="glyphicon glyphicon-stats"></span> Statistics</a></li>
          </ul>
        </div>
      </div>
    </nav>
    

    



<div id="mySidenav" class="sidenav">
  <a href="{{ url_for('equipment.get_equipment') }}"><span class="fa fa-balance-scale"></span> Equipment</a>
  <a href="{{ url_for('experiments.get_experiments') }}"><span class="fa fa-flask"></span> Experiments</a>
  <a href="{{ url_for('measurement.importData') }}"><span class="fa fa-cloud-download"></span> Import</a>
  <a href="{{ url_for('measurement.exportData') }}"><span class="fa fa-cloud-upload"></span> Export</a>
  <a href="{{ url_for('qrgenerator.person_setup_QR') }}"><span class="glyphicon glyphicon-qrcode"></span> QR code persons</a>
  <a href="{{ url_for('qrgenerator.station_setup_QR') }}"><span class="glyphicon glyphicon-qrcode"></span> QR code stations</a>
  <a href="#"><span class="fa fa-database"></span> Storage</a>
  <a href="{{ url_for('fitness.showFood') }}"><span class="fa fa-cutlery"></span> Food</a>
  <!--<a href="#">Other settings</a>-->
</div>




        
        
        <div class="col-md-offset-1 col-md-10 col-md-offset-1 main">
            
            <!------------------------------------------------------------------------>
            <!--<h1 class="page-header">#stopLenochodům!</h1>-->
            {% block content %}{% endblock %}

  

            <!------------------------------------------------------------------------>

        </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>  
    
    
<script>
var opened = false;
function openNav() {
    if(!opened) {
        document.getElementById("mySidenav").style.width = "250px";
        opened = true;
    }
    else {
        document.getElementById("mySidenav").style.width = "0";
        opened = false;
    }
    
}
</script>

  </body>
</html>
 

app/templates/macros.html
{% macro link_to(endpoint, text) -%}
<a href="{{ url_for(endpoint, **kwargs) }}">{{ text|safe }}</a>
{%- endmacro %} 

app/templates/sign_in.html
{% extends "base.html" %}

{% block content %}
{% macro render_field(field, placeholder=None) %}
{% if field.errors %}
<div>
{% elif field.flags.error %}
<div>
{% else %}
<div>
{% endif %}
	{% set css_class = 'form-control ' + kwargs.pop('class', '') %}
	{{ field(class=css_class, placeholder=placeholder, **kwargs) }}
</div>
{% endmacro %}

<div>
	<div>
		<legend>Sign in</legend>
		{% with errors = get_flashed_messages(category_filter=["error"]) %}
		{% if errors %}
		<div>
		{% for error in errors %}
		{{ error }}<br>
		{% endfor %}
		</div>
		{% endif %}
		{% endwith %}

		{% if form.errors %}
		<div>
		{% for field, error in form.errors.items() %}
		{% for e in error %}
		{{ e }}<br>
		{% endfor %}
		{% endfor %}
		</div>
		{% endif %}
		<form method="POST" action="." accept-charset="UTF-8" role="form">
			{{ form.csrf_token }}
			{{ render_field(form.email, placeholder="Your Email Address", autofocus="") }}
			{{ render_field(form.password, placeholder="Password") }}
			<div>
				<label>
					<input type="checkbox" name="remember" value="1"> Remember Me
				</label>
				<a role="button" href="">Forgot your password?</a><span class="clearfix"></span>
			</div>
			<button type="submit" name="submit">Sign in</button>
		</form>  
	</div>
</div>
{% endblock %}

app/templates/sign_up.html
<html>
  <head>
    <title></title>
    <meta content="">
    <style></style>
  </head>
  <body></body>
</html>

app/templates/web-layout.html
{% macro link_to(endpoint, text) -%}
<a href="{{ url_for(endpoint, **kwargs) }}">{{ text|safe }}</a>
{%- endmacro %}


<!DOCTYPE html>
<html>
    <head>
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{{ url_for('static', filename='img/favicon.png') }}">
        
        <title>Body in Numbers</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="{{ url_for('static', filename='web-layout-style.css') }}"> <!-- Resource style -->
        
        <!-- AOS library -->
        <!--<link rel="stylesheet" href="aos/dist/aos.css" />-->
        <link rel="stylesheet" href="{{ url_for('static', filename='aos/dist/aos.css') }}">
        <!--<script src="aos/dist/aos.js"></script>-->
        <script src="{{ url_for('static', filename='aos/dist/aos.js') }}"></script>
        
        
        
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        
        {% block includes %}{% endblock %} 
    </head>
    
    
    
    <body>
        
  <script>
    AOS.init();
    
    $(document).scroll(function() {

  var scrollTop = $(window).scrollTop();
        if (scrollTop >= 200 ) {
            $('.navbar').addClass("nav-down");
            $('.navbar').removeClass("nav-up");
        }
        else{
            $('.navbar').addClass("nav-up");
            $('.navbar').removeClass("nav-down");
        }
});
  </script>
        
        
<aside class="sticky-social">
    <ul>
        <li><a href="https://www.facebook.com/Body-In-Numbers-1451727118215042/?notif_t=fbpage_fan_invite&notif_id=1505392183098950" class="fa fa-facebook"></a></li>
        <li><a href="https://plus.google.com/+PetrBr%C5%AFha" class="fa fa-google"></a></li>
        <li><a href="https://cz.linkedin.com/in/pbruha" class="fa fa-linkedin"></a></li>
        <li><a href="https://play.google.com/store/apps/details?id=com.ionicframework.bc897388" class="fa fa-android"></a></li>
        <li><a href="https://www.researchgate.net/project/Exercise-and-Wellness-Health-Strategy-Framework" class="fa fa-researchgate">R<sup>G</sup></a></li>
    </ul>
</aside>
        
            <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top navbar-custom nav-up">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('general.index') }}">Body in Numbers</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{{ url_for('general.index') }}">Home</a></li>
            <li><a href="{{ url_for('general.index') }}#about">About</a></li>
            <li><a href="{{ url_for('general.index') }}#contacts">Contact</a></li>

          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('statistics.showResultsForm') }}">My results</a></li>
            <li><a href="{{ url_for('general.index') }}">Profile</a></li>
            <li><a href="{{ url_for('auth.login') }}"><span class="blue-bg">App Login</span></a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

        {% block content %}{% endblock %}

    </body>
</html>